"""First autogenerated rivision

Revision ID: 45f7e123c15d
Revises: 1d62649037b2
Create Date: 2013-09-28 15:04:26.464757

"""

# revision identifiers, used by Alembic.
revision = '45f7e123c15d'
down_revision = '1d62649037b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
