"""added latitude and longitude

Revision ID: a768c120671
Revises: 45f7e123c15d
Create Date: 2013-09-28 18:25:48.671557

"""

# revision identifiers, used by Alembic.
revision = 'a768c120671'
down_revision = '45f7e123c15d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'longitude')
    op.drop_column('event', 'latitude')
    ### end Alembic commands ###
